### ISSUE TITLE
Don't hardcode Readme and License for copying to resulting zip

### ISSUE THREAD

**Issue by asonix** [asonix/release-manager#3]
Maybe provide a list of paths to files that should be provided in the resulting zip file with the binary.

Instead of 
```toml
readme = "README.md"
license = "LICENSE"
```
a Release.toml could look like the following:
```toml
included_files = ["README.md", "LICENSE", "acknowledgements.txt"]
```
